modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "zombiesyndrome"
version = "${version}"
displayName = "ZombieSyndrome"
authors = "TeamPancake"
description = '''
A Minecraft Mod.
'''

[[dependencies.zombiesyndrome]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
